# vi: set ft=ruby

# Install vagrant-disksize to allow resizing the vagrant box disk.
unless Vagrant.has_plugin?("vagrant-disksize")
    raise  Vagrant::Errors::VagrantError.new, "vagrant-disksize plugin is missing. Please install it using 'vagrant plugin install vagrant-disksize' and rerun 'vagrant up'"
end

Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "sudo apt-get update && sudo apt-get -y upgrade"

  config.vm.define "ubuntu18" do |ubuntu18|
    ubuntu18.vm.box = "ubuntu/bionic64"
    ubuntu18.vm.provider "virtualbox" do |l|
      l.cpus = 4
      l.memory = "8192"
    end
    ubuntu18.vm.network "forwarded_port", guest: 8800, host: 8800
    ubuntu18.vm.network "forwarded_port", guest: 8080, host: 8080
    ubuntu18.disksize.size = '100GB'

  end
end
